import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

/**
 * Editorial copy for a featured team — a one-line recap and hot/cold player
 * lists — generated by OpenAI with web search so it reflects the team's actual
 * current form, not a stale training snapshot. The model is asked to ground the
 * recap in the real final score we already have.
 *
 * Results are keyed by the team's last final, so each game is generated exactly
 * once; with a persistent store that holds across restarts too. Everything
 * degrades to nothing: no API key, a network error, or an unparseable response
 * yields an empty {} and the card renders without the editorial line. The
 * OpenAI response shape is isolated to this module.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */
type Any = any;

const RESPONSES_URL = "https://api.openai.com/v1/responses";
const DEFAULT_MODEL = "gpt-4o-mini";

/** Hard cap on a recap line so portrait summaries naturally fit in two lines. */
const MAX_SUMMARY_LEN = 100;

/** Hard cap on a displayed player name (the chips are tiny). */
const MAX_NAME_LEN = 11;
/** Names that should always render as a well-known short form. */
const NAME_EXCEPTIONS: Record<string, string> = {
  "crow-armstrong": "PCA",
  "pete crow-armstrong": "PCA",
};

export interface Editorial {
  /** Short recap of the team's most recent game. */
  summary?: string;
}

export interface EditorialContext {
  /** Full team name for the prompt, e.g. "Detroit Tigers". */
  teamName: string;
  /** The real last-game line for grounding, e.g. "L 3-2 vs NYY". */
  lastGameLine?: string;
  /** Identity of the last final (e.g. its date); the cache key. */
  lastFinalKey?: string;
}

/** A minimal key/value store the editorial cache writes through. */
export interface EditorialStore {
  get<T>(key: string): T | undefined;
  set<T>(key: string, value: T): void;
}

export interface EditorialDeps {
  apiKey?: string;
  model?: string;
  store?: EditorialStore;
  fetchImpl?: typeof fetch;
}

export interface EditorialClient {
  generate(
    teamKey: string,
    ctx: EditorialContext,
    opts?: { force?: boolean },
  ): Promise<Editorial>;
  /**
   * Non-blocking accessor: return the cached editorial immediately if present,
   * otherwise kick off generation in the background and return an empty result
   * with `pending: true`. Lets the dashboard respond without waiting on OpenAI;
   * the next refresh picks up the cached result.
   */
  getOrQueue(
    teamKey: string,
    ctx: EditorialContext,
  ): { editorial: Editorial; pending: boolean };
}

/** In-memory store (default). */
export function memoryStore(): EditorialStore {
  const m = new Map<string, unknown>();
  return {
    get: <T>(k: string) => m.get(k) as T | undefined,
    set: <T>(k: string, v: T) => {
      m.set(k, v);
    },
  };
}

/** JSON-file-backed store so generated editorial survives a restart and a game
 * is never regenerated. Read/write failures degrade to in-memory only. */
export function fileStore(path: string): EditorialStore {
  let data: Record<string, unknown> = {};
  try {
    data = JSON.parse(readFileSync(path, "utf8"));
  } catch {
    data = {};
  }
  return {
    get: <T>(k: string) => data[k] as T | undefined,
    set: <T>(k: string, v: T) => {
      data[k] = v;
      try {
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, JSON.stringify(data));
      } catch {
        // persistence is best-effort; keep serving from memory
      }
    },
  };
}

/** Format a game's ISO date as a CT calendar date for prompt grounding. */
function formatGameDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return new Intl.DateTimeFormat("en-US", {
    month: "long",
    day: "numeric",
    timeZone: "America/Chicago",
  }).format(d);
}

function recapPrompt(ctx: EditorialContext): string {
  let grounding = "";
  if (ctx.lastGameLine) {
    const when = ctx.lastFinalKey ? ` on ${formatGameDate(ctx.lastFinalKey)}` : "";
    grounding =
      ` Their most recent game is the one that finished ${ctx.lastGameLine}${when} — ` +
      `this is authoritative. Before writing, confirm that any result, player, or ` +
      `storyline you reference is from THAT exact game (matching opponent and date) ` +
      `and not an earlier game. Treat the result itself as already known — do not ` +
      `restate it.`;
  }
  return (
    `In ${MAX_SUMMARY_LEN} characters or fewer and no more than 16 words, give most relevant talking ` +
    `points about the ${ctx.teamName} after their most recent game. Be as ` +
    `concise as possible. Do NOT state anything obvious from the box score — ` +
    `no final score, no who won or lost, no run/point totals. Focus on the ` +
    `overarching storyline for the team.${grounding} Reply with the sentence ` +
    `only — no preamble, no quotes.`
  );
}

/** Pull the assistant text out of a Responses API payload. */
export function extractResponseText(data: Any): string {
  if (typeof data?.output_text === "string") return data.output_text.trim();
  const parts: string[] = [];
  for (const item of data?.output ?? []) {
    if (item?.type !== "message") continue;
    for (const c of item?.content ?? []) {
      if (c?.type === "output_text" && typeof c.text === "string") parts.push(c.text);
    }
  }
  return parts.join("").trim();
}

/** Clean a recap into a single tidy line, hard-capped at the max length. */
export function cleanSummary(text: string): string | undefined {
  const line = text.replace(/\s+/g, " ").replace(/^["']|["']$/g, "").trim();
  if (!line.length) return undefined;
  if (line.length <= MAX_SUMMARY_LEN) return line;
  const hard = line.slice(0, MAX_SUMMARY_LEN + 1);
  const lastSpace = hard.lastIndexOf(" ");
  return (lastSpace > 0 ? hard.slice(0, lastSpace) : hard.slice(0, MAX_SUMMARY_LEN)).trimEnd();
}

function cleanEditorial(value: Editorial | undefined): Editorial | undefined {
  if (!value || typeof value !== "object") return undefined;
  const out: Editorial = {};
  if (typeof value.summary === "string") {
    const summary = cleanSummary(value.summary);
    if (summary) out.summary = summary;
  }
  return out;
}

/** Apply the special-case short forms and the hard length cap to a name. */
export function shortenPlayerName(name: string): string {
  const trimmed = name.trim();
  const exception = NAME_EXCEPTIONS[trimmed.toLowerCase()];
  if (exception) return exception;
  return trimmed.length > MAX_NAME_LEN ? trimmed.slice(0, MAX_NAME_LEN) : trimmed;
}

/**
 * Build the editorial client. A game's recap is generated at
 * most once (keyed by the last final) and written through the store. The whole
 * per-game attempt is cached, even when empty, so browser refreshes never keep
 * spending OpenAI calls for the same game.
 */
export function createEditorialClient(deps: EditorialDeps = {}): EditorialClient {
  const apiKey = deps.apiKey ?? process.env.OPENAI_API_KEY;
  const model = deps.model ?? process.env.OPENAI_MODEL ?? DEFAULT_MODEL;
  const store = deps.store ?? memoryStore();
  const fetchImpl = deps.fetchImpl ?? fetch;
  const inFlight = new Map<string, Promise<Editorial>>();

  async function ask(prompt: string): Promise<string> {
    const res = await fetchImpl(RESPONSES_URL, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model,
        input: prompt,
        tools: [{ type: "web_search_preview" }],
      }),
    });
    if (!res.ok) throw new Error(`OpenAI ${res.status}`);
    return extractResponseText(await res.json());
  }

  async function piece<T>(
    cacheKey: string,
    produce: () => Promise<T | undefined>,
    isPresent: (v: T | undefined) => boolean,
    force = false,
  ): Promise<T | undefined> {
    if (!force) {
      const cached = store.get<T>(cacheKey);
      if (isPresent(cached)) return cached;
    }
    const value = await produce().catch(() => undefined);
    if (isPresent(value)) store.set(cacheKey, value);
    return value;
  }

  async function generate(
    teamKey: string,
    ctx: EditorialContext,
    opts: { force?: boolean } = {},
  ): Promise<Editorial> {
    if (!apiKey) return {};
    const force = opts.force ?? false;
    const finalKey = ctx.lastFinalKey ?? "none";
    const fullKey = `editorial:game:${teamKey}:${finalKey}`;
    if (!force) {
      const cached = cleanEditorial(store.get<Editorial>(fullKey));
      if (cached) return cached;
    }

    const pending = inFlight.get(fullKey);
    if (pending) return pending;

    const promise = (async () => {
      // Hot/cold now comes from real stats (mlbStats.getHotCold); the LLM only
      // writes the prose summary.
      const summary = await piece<string>(
        `editorial:summary:${teamKey}:${finalKey}`,
        async () => cleanSummary(await ask(recapPrompt(ctx))),
        (v) => typeof v === "string" && v.length > 0,
        force,
      );
      const editorial: Editorial = {};
      if (summary) {
        const clean = cleanSummary(summary);
        if (clean) editorial.summary = clean;
      }
      store.set(fullKey, editorial);
      return editorial;
    })();

    inFlight.set(fullKey, promise);
    try {
      return await promise;
    } finally {
      inFlight.delete(fullKey);
    }
  }

  function getOrQueue(
    teamKey: string,
    ctx: EditorialContext,
  ): { editorial: Editorial; pending: boolean } {
    if (!apiKey) return { editorial: {}, pending: false };
    const finalKey = ctx.lastFinalKey ?? "none";
    const fullKey = `editorial:game:${teamKey}:${finalKey}`;
    const cached = cleanEditorial(store.get<Editorial>(fullKey));
    if (cached) {
      return { editorial: cached, pending: false };
    }
    // Not cached yet: generate in the background (deduped via inFlight, and the
    // attempt is cached even when empty, so this resolves after one pull).
    void generate(teamKey, ctx).catch(() => {});
    return { editorial: {}, pending: true };
  }

  return { generate, getOrQueue };
}
