#!/usr/bin/env python3
"""One-shot generator: convert the watched teams' logos into Spectra-6 bitmaps
baked into firmware/src/logos.h.

This is NOT a pipeline — it is run by hand when a logo is added or changed:

    python3 tools/gen-logos.py

Each source PNG (tools/_src/<name>.png) is flattened onto white, downscaled,
and quantized to the panel's six inks with Floyd-Steinberg dithering. The output
is one byte per pixel holding a palette index 0-5.
"""
import json

from PIL import Image

SIZE = 44  # pixels square, sized to the team-card logo slot

# Palette order MUST match PALETTE[] in render_dashboard.cpp.
# 0=black 1=white 2=red 3=green 4=blue 5=yellow
PALETTE = [
    (0, 0, 0),
    (255, 255, 255),
    (200, 0, 0),
    (0, 120, 55),
    (0, 45, 140),
    (240, 200, 0),
]

# (C symbol, source file, [watched team keys that use this logo])
LOGOS = [
    ("LOGO_TIGERS", "tigers", ["tigers"]),
    ("LOGO_CUBS", "cubs", ["cubs"]),
    ("LOGO_LIONS", "lions", ["lions"]),
    ("LOGO_PISTONS", "pistons", ["pistons"]),
    ("LOGO_MSU", "msu", ["msu-football", "msu-basketball"]),
]

SRC = "tools/_src"
OUT = "firmware/src/logos.h"
# Same pixel data as JSON so the browser preview can render the true device
# output (palette index per pixel), plus a watched-key -> logo-name map.
OUT_JSON = "backend/src/logos.json"


def build_palette_image():
    # Cycle the six colours through all 256 slots so every quantized index maps
    # back to one of our six via (index % 6).
    flat = []
    for i in range(256):
        flat.extend(PALETTE[i % len(PALETTE)])
    pal = Image.new("P", (1, 1))
    pal.putpalette(flat)
    return pal


def quantize(name, pal):
    img = Image.open(f"{SRC}/{name}.png").convert("RGBA")
    # Flatten transparency onto white (the paper colour).
    bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
    img = Image.alpha_composite(bg, img).convert("RGB")
    img = img.resize((SIZE, SIZE), Image.LANCZOS)
    # No dithering: team logos are mostly flat colour regions, so nearest-colour
    # gives clean solid fills. Dithering just adds rainbow speckle here.
    q = img.quantize(palette=pal, dither=Image.NONE)
    return [idx % len(PALETTE) for idx in q.getdata()]


def emit(f, symbol, data):
    f.write(f"static const uint8_t {symbol}[{SIZE * SIZE}] = {{\n")
    for row in range(SIZE):
        chunk = data[row * SIZE:(row + 1) * SIZE]
        f.write("  " + ",".join(str(v) for v in chunk) + ",\n")
    f.write("};\n\n")


def main():
    pal = build_palette_image()
    bitmaps = {name: quantize(name, pal) for _, name, _ in LOGOS}

    with open(OUT, "w") as f:
        f.write("#pragma once\n")
        f.write("#include <Arduino.h>\n\n")
        f.write("// AUTO-GENERATED by tools/gen-logos.py. Do not edit by hand.\n")
        f.write("// One byte per pixel: palette index 0-5\n")
        f.write("// 0=black 1=white 2=red 3=green 4=blue 5=yellow\n\n")
        f.write(f"static const uint16_t LOGO_SIZE = {SIZE};\n\n")
        for symbol, name, _ in LOGOS:
            emit(f, symbol, bitmaps[name])
        f.write("struct Logo { const uint8_t* data; uint16_t size; };\n\n")
        f.write("inline const Logo* logoForKey(const String& key) {\n")
        f.write("  static const Logo tigers{LOGO_TIGERS, LOGO_SIZE};\n")
        f.write("  static const Logo cubs{LOGO_CUBS, LOGO_SIZE};\n")
        f.write("  static const Logo lions{LOGO_LIONS, LOGO_SIZE};\n")
        f.write("  static const Logo pistons{LOGO_PISTONS, LOGO_SIZE};\n")
        f.write("  static const Logo msu{LOGO_MSU, LOGO_SIZE};\n")
        f.write('  if (key == "tigers") return &tigers;\n')
        f.write('  if (key == "cubs") return &cubs;\n')
        f.write('  if (key == "lions") return &lions;\n')
        f.write('  if (key == "pistons") return &pistons;\n')
        f.write('  if (key == "msu-football" || key == "msu-basketball") return &msu;\n')
        f.write("  return nullptr;\n")
        f.write("}\n")

    key_map = {key: name for _, name, keys in LOGOS for key in keys}
    payload = {"size": SIZE, "logos": bitmaps, "keyMap": key_map}
    with open(OUT_JSON, "w") as f:
        json.dump(payload, f)

    print(f"Wrote {OUT} and {OUT_JSON} ({len(LOGOS)} logos at {SIZE}x{SIZE})")


if __name__ == "__main__":
    main()
