#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${OUT:-$ROOT/firmware/src/sf_pro_fonts.h}"

TEXT_FONT="${SF_PRO_TEXT_FONT:-/Library/Fonts/SF-Pro-Text-Regular.otf}"
DISPLAY_FONT="${SF_PRO_DISPLAY_FONT:-/Library/Fonts/SF-Pro-Display-Regular.otf}"

if [[ ! -f "$TEXT_FONT" ]]; then
  echo "SF Pro Text font not found: $TEXT_FONT" >&2
  echo "Set SF_PRO_TEXT_FONT=/path/to/SF-Pro-Text-Regular.otf and retry." >&2
  exit 1
fi

if [[ ! -f "$DISPLAY_FONT" ]]; then
  echo "SF Pro Display font not found: $DISPLAY_FONT" >&2
  echo "Set SF_PRO_DISPLAY_FONT=/path/to/SF-Pro-Display-Regular.otf and retry." >&2
  exit 1
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

build_fontconvert() {
  mkdir -p "$TMP/fontconvert"
  curl -fsSL \
    https://raw.githubusercontent.com/adafruit/Adafruit-GFX-Library/master/fontconvert/fontconvert.c \
    -o "$TMP/fontconvert/fontconvert.c"
  curl -fsSL \
    https://raw.githubusercontent.com/adafruit/Adafruit-GFX-Library/master/gfxfont.h \
    -o "$TMP/gfxfont.h"

  local cflags=""
  local libs=""
  if command -v pkg-config >/dev/null 2>&1 && pkg-config --exists freetype2; then
    cflags="$(pkg-config --cflags freetype2)"
    libs="$(pkg-config --libs freetype2)"
  elif [[ -d /opt/X11/include/freetype2 && -e /opt/X11/lib/libfreetype.dylib ]]; then
    cflags="-I/opt/X11/include/freetype2"
    libs="-L/opt/X11/lib -lfreetype"
  else
    echo "FreeType headers/libs were not found." >&2
    echo "Install FreeType or XQuartz, or set FONTCONVERT=/path/to/fontconvert." >&2
    exit 1
  fi

  cc "$TMP/fontconvert/fontconvert.c" $cflags $libs -o "$TMP/fontconvert_bin"
  echo "$TMP/fontconvert_bin"
}

FONTCONVERT="${FONTCONVERT:-}"
if [[ -z "$FONTCONVERT" ]]; then
  if command -v fontconvert >/dev/null 2>&1; then
    FONTCONVERT="$(command -v fontconvert)"
  else
    FONTCONVERT="$(build_fontconvert)"
  fi
fi

if [[ ! -x "$FONTCONVERT" ]]; then
  echo "FONTCONVERT is not executable: $FONTCONVERT" >&2
  exit 1
fi

emit_font() {
  local src="$1"
  local name="$2"
  local pt="$3"
  ln -sf "$src" "$TMP/$name.otf"
  "$FONTCONVERT" "$TMP/$name.otf" "$pt"
}

mkdir -p "$(dirname "$OUT")"
{
  cat <<'HEADER'
// Generated by tools/gen-sf-pro-fonts.sh from locally installed SF Pro fonts.
// Do not commit this file. It contains bitmap data from a user-supplied font.
#pragma once

#include <Adafruit_GFX.h>

HEADER
  emit_font "$TEXT_FONT" SFProTextRegular 8
  echo
  emit_font "$TEXT_FONT" SFProTextRegular 12
  echo
  emit_font "$DISPLAY_FONT" SFProDisplayRegular 18
} > "$OUT"

echo "Wrote $OUT"
